- name: Query project information
  include: get_project_information.yml
  
- name: Query runner information
  include: get_runner_information.yml

- name: Register new runner
  include: new_runner.yml
  with_items: '{{ [ ansible_gitlab_runners_token|first ] }}'
  loop_control:
    loop_var: first_repo_to_register_to
  when: >-
    gitlab_runner__runner_id|d([]) == [] and ansible_gitlab_runners_token|d([])
    != []
  register: runner_just_registered
  notify: restart gitlab-runner

- name: 'Query runner information, again, if we just registered'
  include: get_runner_information.yml
  when: runner_just_registered.changed

- name: Add runner to additional repossitories
  include: add_to_additional_repo.yml
  with_items: '{{ gitlab_runner__runner_id }}'
  loop_control:
    loop_var: runner
  when: 'ansible_gitlab_runners_token != []'

- name: Remove runner from superseded repossitories
  include: remove_from_superseded_repo.yml
  with_items: '{{ gitlab_runner__runner_id }}'
  loop_control:
    loop_var: runner
  # when: ansible_gitlab_runners_token != [] TODO: find good when condition