- name: Query project information
  include: get_project_information.yml

- name: Query runner information
  include: get_runner_information.yml

- name: GitLab-Runner | Register runner
  docker_container:
    name: '{{ ansible_gitlab_runner_container_name }}'
    state: started
    image: '{{ ansible_gitlab_runner_base_image }}'
    volumes:
      - '{{ ansible_gitlab_runner_project_directory }}/etc:/etc/gitlab-runner:rw'
      - '/var/run/docker.sock:{{ ansible_gitlab_runner_docker_socket_path }}:rw'
    docker_host: 'unix:/{{ ansible_docker_socket_path }}'
    tty: True
    detach: False
    cleanup: True
    command: |-
      {{ 'register --non-interactive' +
        ' --executor "' + ansible_gitlab_runner_executor + '"' +
        ' --docker-image "' + ansible_gitlab_runner_docker_image + '"' +
        ' --url "' + ansible_gitlab_url + '"' +
        ' --registration-token "' + item.token + '"' +
        ' --description "' + ansible_gitlab_runner_description + '"' +
        ' --tag-list "' + (ansible_gitlab_runner_tags | join(',')) + '"' +
        ' --run-untagged="' + (ansible_gitlab_runner_run_untagged | ternary('true', 'false')) + '"' +
        ' --locked="' + (ansible_gitlab_runner_locked | ternary('true', 'false')) + '"' }}
  with_items: '{{ [ ansible_gitlab_runners_token|first ] }}'
  when: 'runner_config.stdout == "" and ansible_gitlab_runners_token|d([]) != []'
  register: runner_just_registered
  notify: restart gitlab-runner

- name: Query runner information, again, if we just registered
  include: get_runner_information.yml
  when: runner_just_registered.changed

# Doing this to archive a nested loop
- name: Add runner to additional repossitories
  include: add_to_additional_repo.yml
  with_items: '{{ gitlab_runner__runner_id }}'
  loop_control:
    loop_var: runner_id
  when: ansible_gitlab_runners_token != []

# TODO: Remove projects that are not in ansible_gitlab_registration_repossitories
# TODO: Get correct runner id to unregister
#- name: GitLab-Runner | Register | remove runner from projects it should no longer be part of.
#  uri:
#    url: '{{ gitlab_runner__projects_api_url }}/{{ item | urlencode() | regex_replace("/","%2F") }}/runners/{{ TODO: runnerID }}'
#    method: DELETE
#    headers:
#      PRIVATE-TOKEN: '{{ ansible_gitlab_api_token }}'
#  with_items: '{{ gitlab_runner__register_api_details_this_runner_associated_projects_pathwithnamespace }}'
#  when: item not in ansible_gitlab_registration_repossitories
